### ISSUE TITLE
depends qtbase-opensource-src URL returned 404 Not Found

### ISSUE THREAD

**Issue by boulder0o** [BITC2/bitcoin2#12]
Fetching qtbase-opensource-src-5.9.7.tar.xz from https://bitcoincore.org/depends-sources
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

**Comment by boulder0o** [comment]
I believe the fix is to change Line 3 of qt.mk in depends/packages/ :

$(package)_download_path=https://download.qt.io/official_releases/qt/5.9/$($(package)_version)/submodules

change to...

$(package)_download_path=https://download.qt.io/archive/qt/5.9/$($(package)_version)/submodules

**Comment by Bitc2org** [comment]
Alright thank you for that. This is how it was updated in Dash project as well so it's done.
